# Generated by Django 4.2.7 on 2023-12-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(default=100, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dev_schema"."department',
            },
        ),
    ]
